sudo: false
language: generic

os:
- linux
- osx

cache:
  # For faster build times.
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

addons:
  apt:
    packages:
    - cmake
    - libgmp-dev       # for cabal

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH

# Install stack.
- |
  if [ $TRAVIS_OS_NAME = linux ]
    then
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    else
      travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  fi

install:
- cd $TRAVIS_BUILD_DIR
#- stack --no-terminal --install-ghc test --only-dependencies --ghc-options=-Werror
- stack build --ghc-options=-Werror

script:
# Compile haddock etc.
- cd $TRAVIS_BUILD_DIR
- stack --no-terminal test --haddock --no-haddock-deps
